### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by madou**
Good day! 
I've translated most of the things (i think so atleast, never worked on GitHub), apart from the "byes" word in PvP stats section. Couldn't find a proper russian word for it, until i understand what that word actually means - i guess it's some other kind of desertion? Would like to hear your comment about it.
Also, i used names from russian GW2 wiki to translate attributes and classes names to avoid confusion among russian players :D

Hope i did everything right. Please let me know if i can help with anything else, or if you need something changed.

Best regards, MilesRed

### CODE REVIEW

**Comment by madou** [comment]
@MilesRed hey!

this is a wiki for byes: https://en.wikipedia.org/wiki/Bye_(sports)

**Comment by madou** [comment]
@MilesRed i'll merge this and we can make changes later :)

**Comment by MilesRed** [comment]
@madou i knew i messed up with submitting :D 
I guess the best russian word for "byes" would be "Фора" - maybe you can just change it yourself, without me stumbling around here again :)
Also, do i need to press that Delete Branch button up there?

**Comment by madou** [comment]
you can delete it if you want :D

cool ill add that word in directly, thanks man!

**Comment by MilesRed** [comment]
Sweet! Well, if you'll need me in the future - feel free to message me on Reddit or something :)

**Comment by madou** [comment]
sure will do. are you limited to just russian translations or are you keen for javascript too? ;)

**Comment by MilesRed** [comment]
Only translations, sadly :(

**Comment by madou** [comment]
all good, thanks again!

**Pull request merged**
